use GD1C2013
go

DROP TRIGGER DATACENTER.act_precio_reco
DROP TABLE DATACENTER.Devolucion
DROP TABLE DATACENTER.Pasaje
DROP TABLE DATACENTER.Arribo
DROP TABLE DATACENTER.Butaca
DROP TABLE DATACENTER.Canje
DROP TABLE DATACENTER.Premio
DROP TABLE DATACENTER.Paquete
DROP TABLE DATACENTER.Compra
DROP TABLE DATACENTER.TipoTarjeta
DROP TABLE DATACENTER.Viaje
DROP TABLE DATACENTER.Recorrido
DROP TABLE DATACENTER.EstadoMicro
DROP TABLE DATACENTER.Micro
DROP TABLE DATACENTER.Servicio
DROP TABLE DATACENTER.Cliente
DROP TABLE DATACENTER.Marca
DROP TABLE DATACENTER.FuncionalidadPorRol
DROP TABLE DATACENTER.Funcionalidad
DROP TABLE DATACENTER.Ciudad
DROP TABLE DATACENTER.Usuario
DROP TABLE DATACENTER.Rol

DROP VIEW Micros_Migrados

DROP PROCEDURE DATACENTER.update_cant_intentos_fallidos
DROP PROCEDURE DATACENTER.insert_Rol
DROP PROCEDURE DATACENTER.insert_funcxrol
DROP PROCEDURE DATACENTER.delete_funcxrol
DROP PROCEDURE DATACENTER.delete_rol
DROP PROCEDURE DATACENTER.update_rol
DROP PROCEDURE DATACENTER.get_listado_viaje
DROP PROCEDURE DATACENTER.cargar_campos_cliente
DROP PROCEDURE DATACENTER.get_butacas
DROP PROCEDURE DATACENTER.get_costo_encomienda
DROP PROCEDURE DATACENTER.get_porcentaje 
DROP PROCEDURE DATACENTER.insert_Cliente
DROP PROCEDURE DATACENTER.update_Cliente
DROP PROCEDURE DATACENTER.get_kg_disponibles
DROP PROCEDURE DATACENTER.check_tipo_tarjeta
DROP PROCEDURE DATACENTER.insert_compra
DROP PROCEDURE DATACENTER.insert_pasaje
DROP PROCEDURE DATACENTER.get_micro_patente
DROP PROCEDURE DATACENTER.insert_paquete

DROP FUNCTION DATACENTER.get_id_viaje

DROP FUNCTION DATACENTER.estado_puntos

DROP FUNCTION DATACENTER.totalPuntosVencidos

DROP FUNCTION DATACENTER.totalPuntos

DROP PROCEDURE DATACENTER.actualizarPuntos

DROP procedure DATACENTER.registrarPuntos

DROP procedure DATACENTER.update_fecha_llegada

DROP function DATACENTER.puntosParaSemestre

DROP function DATACENTER.diasFueraDeServicio

DROP function DATACENTER.sumaDias

DROP FUNCTION DATACENTER.fechaFinSemestre

DROP FUNCTION DATACENTER.fechaInicioSemestre

DROP PROCEDURE DATACENTER.canjeaPremio

DROP PROCEDURE DATACENTER.registraDevolucionParcial

DROP PROCEDURE DATACENTER.registraDevolucionTotal

DROP PROCEDURE DATACENTER.registrarNuevoMicro

DROP PROCEDURE DATACENTER.cancelaViajesXMicro

DROP FUNCTION DATACENTER.estadoBaja

DROP FUNCTION DATACENTER.microDisponible

DROP FUNCTION DATACENTER.verificaStock

DROP PROCEDURE DATACENTER.insert_recorrido
DROP PROCEDURE DATACENTER.update_recorrido
DROP PROCEDURE DATACENTER.update_estado_reco
DROP PROCEDURE DATACENTER.habilitar_estado_reco
DROP PROCEDURE DATACENTER.insert_viaje

DROP SCHEMA DATACENTER






